# Generated by Django 6.0.7 on 2026-07-29 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0003_clubsetting_about_us_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, default='Codician Club is an elite network of developers and creators pushing the boundaries of modern software engineering. We are a community-driven organization dedicated to fostering innovation, collaboration, and continuous learning among tech enthusiasts. Whether you are a beginner taking your first steps in coding or an experienced developer building complex architectures, Codician provides the platform, resources, and mentorship to help you build the future.')),
            ],
        ),
        migrations.RemoveField(
            model_name='clubsetting',
            name='about_us_text',
        ),
    ]
