# Generated by Django 6.0.7 on 2026-07-29 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0004_aboutus_remove_clubsetting_about_us_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Global Institute of Technology', max_length=255)),
                ('description', models.TextField(default='Established in 1995, our college is a premier institution dedicated to advancing technology and fostering innovation. Recognized nationally for its cutting-edge research facilities and exceptional faculty, it serves as the perfect incubator for the Codician Club to thrive and build the future.')),
                ('image', models.ImageField(blank=True, null=True, upload_to='college/')),
                ('accreditations', models.CharField(default='NAAC A++ Accredited, Top 10 Engineering', help_text='Comma separated values', max_length=255)),
            ],
        ),
    ]
