# Generated by Django 6.0.7 on 2026-07-30 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0008_leadership'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leadership',
            name='email',
        ),
        migrations.AddField(
            model_name='leadership',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
    ]
