# Generated by Django 6.0.7 on 2026-07-30 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0009_remove_leadership_email_leadership_linkedin'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreTeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('course', models.CharField(max_length=100)),
                ('semester', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='core_team/')),
            ],
        ),
    ]
