# Generated by Django 6.0.3 on 2026-07-31 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0010_coreteammember'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='college',
            name='accreditations',
        ),
        migrations.AddField(
            model_name='college',
            name='location',
            field=models.URLField(default='https://maps.google.com/?q=Amity+University+Raipur', help_text='Google Maps URL for the college location', max_length=500),
        ),
        migrations.AlterField(
            model_name='college',
            name='name',
            field=models.CharField(default='Amity University Raipur', max_length=255),
        ),
    ]
