# Generated by Django 6.0.3 on 2026-07-31 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0011_remove_college_accreditations_college_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='location_name',
            field=models.CharField(default='Amity University Raipur, Chhattisgarh', help_text='Text to display for the location link', max_length=255),
        ),
    ]
