# Generated by Django 6.0.7 on 2026-08-01 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0013_candidate_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubsetting',
            name='tagline',
            field=models.CharField(default='Where coders become innovators', max_length=255),
        ),
    ]
