# Generated by Django 6.0.7 on 2026-08-01 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0014_clubsetting_tagline'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubsetting',
            name='email',
            field=models.EmailField(default='club.codician@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='clubsetting',
            name='instagram_url',
            field=models.URLField(default='https://www.instagram.com/codician_club_official/', max_length=500),
        ),
        migrations.AddField(
            model_name='clubsetting',
            name='linkedin_url',
            field=models.URLField(default='https://www.linkedin.com/company/codician-club/', max_length=500),
        ),
    ]
